language: node_js
node_js:
- '6.1'
notifications:
  slack:
    on_success: change
    secure: VP5m+haQx3scwaQZc/MLD5jQVN5dWclp0Psb8a65wtEOcst17omH3KqQBg+hsVfzbTETlnYQndOQ3hG0WCj6O/tKM0dzspoWv91AZ1R3BVjJJ+97vnusEUAx1+75iSN/bNBjyAZ7mQyKKyHlLxUAREhKIYr+R+mjl4Xbkmz1ufToc4Z9u25jyt5KB7PmeAyFVxcI+bgHegRavDJaeI965S4tTzI5e9+C+5ILNGukF32SssZybuGb4BZFnKQVqXWKqlDCfQ3/b9zK7TEv5+6AOT5uWcZPo6WXPJ3UA89vA/ArtLtgmw8IN1JTBjrQtlToI2n5hXYoN13n3Kexg5Aw366MOkRjAgISGGi7nA2SppxIdt0JRafzgYA8FuSWfShbY7rI/rIVtT6j5tcTv64MgmpZSVDYd49907s7bvOeIPzURXzHwtlO+zgsU9OlIZH769xMFS5CA7xoCxJxaW8eGSwJsNdi0ck/E5IitZu807LBfnDZ2TA4kJTkmMGLmGRrk2giRXEzNClupVX9Xgy0LqnhoyTWhJFUmbbPXlMpUf97AYIabFAYBTLddsj353XPxwZESMgpnw8OFzqwoXLSQvrh4BkdBgdJvTRVycQS/G0QpOEIfkTUNN+3aC/kwKytbk+wfHY78ZhJ6zsK8yDGfVv/7RkqFTdOlif8BBLsHuQ=
